# AUTO-GENERATED — do not edit; source: contracts/event-envelope.schema.json
# Requirement IDs: TRN-01, TRN-02, TRN-06

# generated by datamodel-codegen:
#   filename:  event-envelope.schema.json
#   timestamp: 2026-08-22T17:31:46+00:00

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class EventEnvelope(TypedDict, closed=True):
    """
    Generic live-process event — TRN-01/TRN-02/TRN-06. No domain noun is a first-class field; payload is arbitrary.
    """

    step_id: str
    status: Literal['started', 'streaming', 'done', 'error']
    payload: dict[str, Any]
    timestamp: str
    sequence: int
    trace_id: NotRequired[str]
    degraded: NotRequired[bool]


class DegradedResult(TypedDict, closed=True):
    degraded: Literal[True]
    reason: str
    fallback_source: Literal['secondary_provider', 'cache', 'replay', 'none']
    original_error: NotRequired[str | None]
    data: NotRequired[dict[str, Any] | list[Any] | str | float | bool | None]
    timestamp: str
    version: Literal['1.0.0']


DegradedResultRef: TypeAlias = DegradedResult
